export const colors = {
  cost: {
    1: 'LightGrey',
    2: 'MediumPurple',
    3: 'Blue',
    4: 'Magenta',
    5: 'DarkOrange',
  },
  features: {
    Dragon: 'Maroon',
    Yordle: 'Chocolate',
    Demon: 'BlueViolet',
    Robot: 'DeepSkyBlue',
    Glacial: 'DodgerBlue',
    Phantom: 'Grey',
    Ninja: 'Red',
    Imperial: 'FireBrick',
    Pirate: 'Yellow',
    Noble: 'White',
    Exile: 'MediumBlue',
    Void: 'Silver',
    Wild: 'Green',
    Assassin: 'Khaki',
    Elementalist: 'Indigo',
    Brawler: 'DarkOrange',
    Ranger: 'SpringGreen',
    Knight: 'Pink',
    Sorcerer: 'Turquoise',
    Gunslinger: 'Sienna',
    Guardian: 'Blue',
    Shapeshifter: 'MediumPurple',
    Blademaster: 'PeachPuff',
  },
};
